ProjetoFinalFaculdade/Models/Professor.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ProjetoFinalFaculdade.Models
{
    public class Professor
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "CPF")]
        public string CPF { get; set; }

        [Required]
        [Display(Name = "Matricula")]
        public int? Matricula { get; set; }

        [Display(Name = "Data de Nascimento")]
        public DateTime? DataNascimento { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Telefone")]
        public int? Telefone { get; set; }

    }
}

ProjetoFinalFaculdade/Controllers/ProfessorController.cs
using ProjetoFinalFaculdade.Models;
using System.Linq;
using System.Web.Mvc;

namespace ProjetoFinalFaculdade.Controllers {
    public class ProfessorController : Controller {

        private ApplicationDbContext _context;


        public ProfessorController() {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing) {
            _context.Dispose();
        }

        // GET: Professor
        public ActionResult Index() {
            var professores = _context.Professores.ToList();
            if (User.IsInRole(RoleName.CanManageData))
                return View(professores);

            return View("ReadOnlyIndex", professores);
        }

        public ActionResult Details(int id) {
            var professor = _context.Professores.SingleOrDefault(p => p.Id == id);
            if (professor == null) {
                return HttpNotFound();
            }

            return View(professor);
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult New() {
            var professor = new Professor();

            return View("ProfessorForm", professor);
        }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Save(Professor professor) // recebemos um professor
        {
            if (!ModelState.IsValid) {
                return View("ProfessorForm", professor);
            }

            if (professor.Id == 0) {
                // armazena o cliente em memória
                _context.Professores.Add(professor);
            } else {
                var professorInDb = _context.Professores.Single(c => c.Id == professor.Id);

                professorInDb.Nome = professor.Nome;
                professorInDb.CPF = professor.CPF;
                professorInDb.Matricula = professor.Matricula;
                professorInDb.DataNascimento = professor.DataNascimento;
                professorInDb.Email = professor.Email;
                professorInDb.Telefone = professor.Telefone;

            }

            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("Index");
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Edit(int id) {
            var professor = _context.Professores.SingleOrDefault(c => c.Id == id);

            if (professor == null)
                return HttpNotFound();


            return View("ProfessorForm", professor);
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Delete(int id) {
            var professor = _context.Professores.SingleOrDefault(c => c.Id == id);

            if (professor == null)
                return HttpNotFound();

            _context.Professores.Remove(professor);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }
    }
}

ProjetoFinalFaculdade/Views/Professor/Details.cshtml
@model ProjetoFinalFaculdade.Models.Professor
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<p>CPF: @Model.CPF</p>
<p>Matricula: @Model.Matricula</p>
<p>Data nascimento: @Model.DataNascimento</p>
<p>Email: @Model.Email</p>
<p>Telefone: @Model.Telefone</p>

ProjetoFinalFaculdade/Views/Professor/Index.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Professor>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Professores</h2>


<p>
    @Html.ActionLink("Novo Professor", "New", null, new { @class = "btn btn-primary" })
</p>

@if (@Model.Any())
{

    <table id="professores" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Matrícula</th>
                <th>Email</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var professor in Model)
            {
                <tr>
                    <td> @Html.ActionLink(professor.Nome, "Details", new { professor.Id })</td>
                    <td> @professor.Matricula</td>
                    <td> @professor.Email</td>
                    <td>
                        <p>
                            @Html.ActionLink(" ", "Edit", new { professor.Id }, new { @class = "glyphicon glyphicon-pencil" })
                        </p>
                    </td>
                    <td>
                        <button class="btn-link js-delete" data-professor-id="@professor.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não existem alunos cadastrados.</p>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#professores").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Quer remover o registro?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/professor/delete/" + button.attr("data-professor-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });

            });
        });
    </script>
}

ProjetoFinalFaculdade/Views/Professor/ProfessorForm.cshtml
@model ProjetoFinalFaculdade.Models.Professor
@{
    ViewBag.Title = Model.Id == 0 ? "Novo Professor" : "Editar Professor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Professor"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CPF)
        @Html.TextBoxFor(m => m.CPF, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CPF)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Matricula)
        @Html.TextBoxFor(m => m.Matricula, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Matricula)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DataNascimento)
        @Html.TextBoxFor(m => m.DataNascimento, "{0:dd/MM/yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.DataNascimento)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Telefone)
        @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
   
}

ProjetoFinalFaculdade/Views/Professor/ReadOnlyIndex.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Professor>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Professores</h2>


@if (@Model.Any()) {

    <table id="professores" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Matrícula</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var professor in Model) {
                <tr>
                    <td> @Html.ActionLink(professor.Nome, "Details", new { professor.Id })</td>
                    <td> @professor.Matricula</td>
                    <td> @professor.Email</td>
                </tr>
            }
        </tbody>
    </table>
} else {
    <p>Não existem alunos cadastrados.</p>
}