ProjetoFinalFaculdade/Models/Aluno.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ProjetoFinalFaculdade.Models
{
    public class Aluno
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "CPF")]
        public string CPF { get; set; }

        [Required]
        [Display(Name = "Matricula")]
        public int? Matricula { get; set; }

        [ValidaIdadeMinimaAluno]
        [Display(Name = "Data de nascimento")]
        public DateTime? DataNascimento { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Telefone")]
        public int? Telefone { get; set; }
        
        public Curso Curso { get; set; }

        //Chave estrangeira
        [Required]
        [Display(Name = "Curso")]
        public int CursoId { get; set; }

        [Required]
        [Display(Name = "Fase")]
        public int? Fase { get; set; }
    }
}

ProjetoFinalFaculdade/Controllers/AlunoController.cs
using ProjetoFinalFaculdade.Models;
using ProjetoFinalFaculdade.ViewModels;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace ProjetoFinalFaculdade.Controllers {

    public class AlunoController : Controller {

        private ApplicationDbContext _context;

        public AlunoController() {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing) {
            _context.Dispose();
        }

        // GET: Aluno
        public ActionResult Index() {
            var alunos = _context.Alunos.Include(c => c.Curso).ToList();
            if (User.IsInRole(RoleName.CanManageData))
                return View(alunos);

            return View("ReadOnlyIndex", alunos);
        }

        public ActionResult Details(int id) {

            var aluno = _context.Alunos.Include(c => c.Curso).SingleOrDefault(a => a.Id == id);
            if (aluno == null) {
                return HttpNotFound();
            }

            return View(aluno);
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult New() {
            var cursos = _context.Cursos.ToList();
            var viewModel = new AlunoIndexViewModel {
                Aluno = new Aluno(),
                Cursos = cursos
            };

            return View("AlunoForm", viewModel);
        }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Save(Aluno aluno) // recebemos um aluno
        {
            if (!ModelState.IsValid) {
                var viewModel = new AlunoIndexViewModel {
                    Aluno = aluno,
                    Cursos = _context.Cursos.ToList()
                };

                return View("AlunoForm", viewModel);
            }

            if (aluno.Id == 0) {
                // armazena o cliente em memória
                _context.Alunos.Add(aluno);
            } else {
                var alunoInDb = _context.Alunos.Single(c => c.Id == aluno.Id);

                alunoInDb.Nome = aluno.Nome;
                alunoInDb.CPF = aluno.CPF;
                alunoInDb.Matricula = aluno.Matricula;
                alunoInDb.DataNascimento = aluno.DataNascimento;
                alunoInDb.Email = aluno.Email;
                alunoInDb.Telefone = aluno.Telefone;
                alunoInDb.CursoId = aluno.CursoId;
                alunoInDb.Fase = aluno.Fase;

            }

            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("Index");
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Edit(int id) {
            var aluno = _context.Alunos.SingleOrDefault(c => c.Id == id);

            if (aluno == null)
                return HttpNotFound();

            var viewModel = new AlunoIndexViewModel {
                Aluno = aluno,
                Cursos = _context.Cursos.ToList()
            };

            return View("AlunoForm", viewModel);
        }


        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Delete(int id) {
            var aluno = _context.Alunos.SingleOrDefault(c => c.Id == id);

            if (aluno == null)
                return HttpNotFound();

            _context.Alunos.Remove(aluno);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }

    }
}

ProjetoFinalFaculdade/Views/Aluno/AlunoForm.cshtml
@model ProjetoFinalFaculdade.ViewModels.AlunoIndexViewModel
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Aluno"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Aluno.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Nome)
        @Html.TextBoxFor(m => m.Aluno.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.CPF)
        @Html.TextBoxFor(m => m.Aluno.CPF, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.CPF)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Matricula)
        @Html.TextBoxFor(m => m.Aluno.Matricula, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.Matricula)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.DataNascimento)
        @Html.TextBoxFor(m => m.Aluno.DataNascimento, "{0:dd/MM/yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.DataNascimento)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Email)
        @Html.TextBoxFor(m => m.Aluno.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Telefone)
        @Html.TextBoxFor(m => m.Aluno.Telefone, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.CursoId)
        @Html.DropDownListFor(m => m.Aluno.CursoId,
            new SelectList(Model.Cursos, "Id", "Nome"),
            "Escolha", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.CursoId)

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Fase)
        @Html.TextBoxFor(m => m.Aluno.Fase, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.Fase)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
   
}

ProjetoFinalFaculdade/Views/Aluno/Details.cshtml
@model ProjetoFinalFaculdade.Models.Aluno
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<p>CPF: @Model.CPF</p>
<p>Matricula: @Model.Matricula</p>
<p>Data nascimento: @Model.DataNascimento</p>
<p>Email: @Model.Email</p>
<p>Telefone: @Model.Telefone</p>
<p>Curso: @Model.Curso.Nome</p>
<p>Fase: @Model.Fase</p>

ProjetoFinalFaculdade/Views/Aluno/Index.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Aluno>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alunos</h2>

<p>
    @Html.ActionLink("Novo Aluno", "New", null, new { @class = "btn btn-primary" })
</p>

@if (@Model.Any()) {
    <table id="alunos" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Matricula</th>
                <th>Email</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var aluno in Model) {
                <tr>
                    <td> @Html.ActionLink(@aluno.Nome, "Details", new { aluno.Id })</td>
                    <td> @aluno.Matricula</td>
                    <td> @aluno.Email</td>
                    <td>
                        <p>

                            @Html.ActionLink(" ", "Edit", new { aluno.Id }, new { @class = "glyphicon glyphicon-pencil" })
                        </p>
                    </td>
                    <td>
                        <button class="btn-link js-delete" data-aluno-id="@aluno.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
} else {
    <p>Não existem alunos cadastrados.</p>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#alunos").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Quer remover o registro?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/aluno/delete/" + button.attr("data-aluno-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });

            });
        });
    </script>
}

ProjetoFinalFaculdade/Views/Aluno/ReadOnlyIndex.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Aluno>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alunos</h2>


@if (@Model.Any()) {
    <table id="alunos" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Matricula</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var aluno in Model) {
                <tr>
                    <td> @Html.ActionLink(@aluno.Nome, "Details", new { aluno.Id })</td>
                    <td> @aluno.Matricula</td>
                    <td> @aluno.Email</td>
                   
                </tr>
            }
        </tbody>
    </table>
} else {
    <p>Não existem alunos cadastrados.</p>
}