ProjetoFinalFaculdade/Models/Curso.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjetoFinalFaculdade.Models
{
    public class Curso
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Ementa")]
        public string Ementa { get; set; }

        [Required]
        [Display(Name = "Duração (em anos)")]
        public string Duracao { get; set; }

        [Required]
        [Display(Name = "Mensalidade")]
        public double? Mensalidade { get; set; }

        [Required]
        [Display(Name = "Coordenador")]
        public string Coordenador { get; set; }
    }
}

ProjetoFinalFaculdade/Controllers/CursoController.cs
using ProjetoFinalFaculdade.Models;
using System.Linq;
using System.Web.Mvc;

namespace ProjetoFinalFaculdade.Controllers {
    public class CursoController : Controller {

        private ApplicationDbContext _context;


        public CursoController() {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing) {
            _context.Dispose();
        }


        // GET: Curso
        public ActionResult Index() {
            var cursos = _context.Cursos.ToList();
            if (User.IsInRole(RoleName.CanManageData))
                return View(cursos);

            return View("ReadOnlyIndex", cursos);
        }

        public ActionResult Details(int id) {
            var curso = _context.Cursos.SingleOrDefault(c => c.Id == id);
            if (curso == null) {
                return HttpNotFound();
            }

            return View(curso);
        }

        [Authorize(Roles = "CanManageData")]
        public ActionResult New() {
            var curso = new Curso();

            return View("CursoForm", curso);
        }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "CanManageData")]
        public ActionResult Save(Curso curso) // recebemos um cliente
        {

            if (!ModelState.IsValid) {
                return View("CursoForm", curso);
            }

            if (curso.Id == 0) {
                // armazena o cliente em memória
                _context.Cursos.Add(curso);
            } else {
                var cursoInDb = _context.Cursos.Single(c => c.Id == curso.Id);

                cursoInDb.Nome = curso.Nome;
                cursoInDb.Ementa = curso.Ementa;
                cursoInDb.Duracao = curso.Duracao;
                cursoInDb.Mensalidade = curso.Mensalidade;
                cursoInDb.Coordenador = curso.Coordenador;

            }

            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "CanManageData")]
        public ActionResult Edit(int id) {
            var curso = _context.Cursos.SingleOrDefault(c => c.Id == id);

            if (curso == null)
                return HttpNotFound();


            return View("CursoForm", curso);
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Delete(int id) {
            var curso = _context.Cursos.SingleOrDefault(c => c.Id == id);

            if (curso == null)
                return HttpNotFound();

            _context.Cursos.Remove(curso);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }
    }
}

ProjetoFinalFaculdade/Views/Curso/CursoForm.cshtml
@model ProjetoFinalFaculdade.Models.Curso
@{
    ViewBag.Title = Model.Id == 0 ? "Novo Curso" : "Editar Curso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Curso"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Ementa)
        @Html.TextBoxFor(m => m.Ementa, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ementa)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Duracao)
        @Html.TextBoxFor(m => m.Duracao, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Duracao)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Mensalidade)
        @Html.TextBoxFor(m => m.Mensalidade, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Mensalidade)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Coordenador)
        @Html.TextBoxFor(m => m.Coordenador, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Coordenador)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
  
}

ProjetoFinalFaculdade/Views/Curso/Details.cshtml
@model ProjetoFinalFaculdade.Models.Curso
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<p>Ementa: @Model.Ementa</p>
<p>Duracao: @Model.Duracao</p>
<p>Mensalidade: @Model.Mensalidade</p>
<p>Coordenador: @Model.Coordenador</p>

ProjetoFinalFaculdade/Views/Curso/Index.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Curso>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cursos</h2>

<p>
    @Html.ActionLink("Novo Curso", "New", null, new { @class = "btn btn-primary" })
</p>

@if (@Model.Any())
{
    <table id="cursos" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Ementa</th>
                <th>Duração</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var curso in Model)
            {
                <tr>
                    <td> @Html.ActionLink(@curso.Nome, "Details", new { curso.Id })</td>
                    <td> @curso.Ementa</td>
                    <td> @curso.Duracao</td>
                    <td>
                        <p>
                            @Html.ActionLink(" ", "Edit", new { curso.Id }, new { @class = "glyphicon glyphicon-pencil" })
                        </p>
                    </td>
                    <td>
                        <button class="btn-link js-delete" data-curso-id="@curso.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não existem alunos cadastrados.</p>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#cursos").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Quer remover o registro?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/curso/delete/" + button.attr("data-curso-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });

            });
        });
    </script>
}

ProjetoFinalFaculdade/Views/Curso/ReadOnlyIndex.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Curso>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cursos</h2>

@if (@Model.Any())
{
    <table id="cursos" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Ementa</th>
                <th>Duração</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var curso in Model)
            {
                <tr>
                    <td> @Html.ActionLink(@curso.Nome, "Details", new { curso.Id })</td>
                    <td> @curso.Ementa</td>
                    <td> @curso.Duracao</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não existem alunos cadastrados.</p>
}