ProjetoFinalFaculdade/Models/Disciplina.cs
using System.ComponentModel.DataAnnotations;

namespace ProjetoFinalFaculdade.Models
{
    public class Disciplina
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Ementa")]
        public string Ementa { get; set; }

        [Required]
        [Display(Name = "Carga horária (em horas)")]
        public double? CargaHoraria { get; set; }

        public Professor Professor { get; set; }

        //Chave estrangeira
        [Required]
        [Display(Name = "Professor")]
        public int? ProfessorId { get; set; }

        public Curso Curso { get; set; }

        //Chave estrangeira
        [Required]
        [Display(Name = "Curso")]
        public int? CursoId { get; set; }

    }
}

ProjetoFinalFaculdade/Controllers/DisciplinaController.cs
using ProjetoFinalFaculdade.Models;
using ProjetoFinalFaculdade.ViewModels;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace ProjetoFinalFaculdade.Controllers {
    public class DisciplinaController : Controller {
        private ApplicationDbContext _context;


        public DisciplinaController() {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing) {
            _context.Dispose();
        }


        // GET: Disciplina
        public ActionResult Index() {
            var disciplinas = _context.Disciplinas.Include(p => p.Professor).Include(c => c.Curso).ToList();
            if (User.IsInRole(RoleName.CanManageData))
                return View(disciplinas);

            return View("ReadOnlyIndex", disciplinas);
        }

        public ActionResult Details(int id) {
            var disciplina = _context.Disciplinas.Include(p => p.Professor).Include(c => c.Curso).SingleOrDefault(d => d.Id == id);
            if (disciplina == null) {
                return HttpNotFound();
            }
            return View(disciplina);
        }

        [Authorize(Roles = "CanManageData")]
        public ActionResult New() {
            var professores = _context.Professores.ToList();
            var cursos = _context.Cursos.ToList();
            var viewModel = new DisciplinaIndexViewModel {
                Professores = professores,
                Cursos = cursos,
                Disciplina = new Disciplina()
            };

            return View("DisciplinaForm", viewModel);
        }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "CanManageData")]
        public ActionResult Save(Disciplina disciplina) // recebemos um cliente
        {
            if (!ModelState.IsValid) {
                var viewModel = new DisciplinaIndexViewModel {
                    Disciplina = disciplina,
                    Professores = _context.Professores.ToList()
                };

                return View("DisciplinaForm", viewModel);
            }

            if (disciplina.Id == 0) {
                // armazena o cliente em memória
                _context.Disciplinas.Add(disciplina);
            } else {
                var disciplinaInDb = _context.Disciplinas.Single(c => c.Id == disciplina.Id);

                disciplinaInDb.Nome = disciplina.Nome;
                disciplinaInDb.Ementa = disciplina.Ementa;
                disciplinaInDb.CargaHoraria = disciplina.CargaHoraria;
                disciplinaInDb.ProfessorId = disciplina.ProfessorId;
                disciplinaInDb.CursoId = disciplina.CursoId;

            }

            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "CanManageData")]
        public ActionResult Edit(int id) {
            var disciplina = _context.Disciplinas.SingleOrDefault(c => c.Id == id);

            if (disciplina == null)
                return HttpNotFound();

            var viewModel = new DisciplinaIndexViewModel {
                Disciplina = disciplina,
                Professores = _context.Professores.ToList(),
                Cursos = _context.Cursos.ToList()
            };

            return View("DisciplinaForm", viewModel);
        }

        [Authorize(Roles = RoleName.CanManageData)]
        public ActionResult Delete(int id) {
            var disciplina = _context.Disciplinas.SingleOrDefault(c => c.Id == id);

            if (disciplina == null)
                return HttpNotFound();

            _context.Disciplinas.Remove(disciplina);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }
    }
}

ProjetoFinalFaculdade/Views/Disciplina/Details.cshtml
@model ProjetoFinalFaculdade.Models.Disciplina
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<p>Ementa: @Model.Ementa</p>
<p>Carga horária: @Model.CargaHoraria</p>
<p>Professor: @Model.Professor.Nome</p>
<p>Curso: @Model.Curso.Nome</p>

ProjetoFinalFaculdade/Views/Disciplina/DisciplinaForm.cshtml
@model ProjetoFinalFaculdade.ViewModels.DisciplinaIndexViewModel
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Disciplina"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Disciplina.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Disciplina.Nome)
        @Html.TextBoxFor(m => m.Disciplina.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Disciplina.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Disciplina.Ementa)
        @Html.TextBoxFor(m => m.Disciplina.Ementa, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Disciplina.Ementa)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Disciplina.CargaHoraria)
        @Html.TextBoxFor(m => m.Disciplina.CargaHoraria, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Disciplina.CargaHoraria)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Disciplina.ProfessorId)
        @Html.DropDownListFor(m => m.Disciplina.ProfessorId,
            new SelectList(Model.Professores, "Id", "Nome"),
            "Escolha", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Disciplina.ProfessorId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Disciplina.CursoId)
        @Html.DropDownListFor(m => m.Disciplina.CursoId,
            new SelectList(Model.Cursos, "Id", "Nome"),
            "Escolha", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Disciplina.CursoId)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    
}

ProjetoFinalFaculdade/Views/Disciplina/Index.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Disciplina>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Disciplinas</h2>

<p>
    @Html.ActionLink("Nova Disciplina", "New", null, new { @class = "btn btn-primary" })
</p>

@if (@Model.Any())
{
    
    <table id="disciplinas" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Ementa</th>
                <th>Carga horária</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var disciplina in Model)
            {
                <tr>
                    <td> @Html.ActionLink(disciplina.Nome, "Details", new { disciplina.Id })</td>
                    <td> @disciplina.Ementa</td>
                    <td> @disciplina.CargaHoraria</td>
                    <td>
                        <p>
                            @Html.ActionLink(" ", "Edit", new { disciplina.Id }, new { @class = "glyphicon glyphicon-pencil" })
                        </p>
                    </td>
                    <td>
                        <button class="btn-link js-delete" data-disciplina-id="@disciplina.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não existem disciplinas cadastradas.</p>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#disciplinas").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Quer remover o registro?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/disciplina/delete/" + button.attr("data-disciplina-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });

            });
        });
    </script>
}

ProjetoFinalFaculdade/Views/Disciplina/ReadOnlyIndex.cshtml
@model IEnumerable<ProjetoFinalFaculdade.Models.Disciplina>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Disciplinas</h2>

@if (@Model.Any()) {

    <table id="disciplinas" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Ementa</th>
                <th>Carga horária</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var disciplina in Model) {
                <tr>
                    <td> @Html.ActionLink(disciplina.Nome, "Details", new { disciplina.Id })</td>
                    <td> @disciplina.Ementa</td>
                    <td> @disciplina.CargaHoraria</td>
                </tr>
            }
        </tbody>
    </table>
} else {
    <p>Não existem disciplinas cadastradas.</p>
}